2022-01-15 14:41:17,123 INFO    MainThread:1956 [internal.py:wandb_internal():87] W&B internal server running at pid: 1956, started at: 2022-01-15 14:41:17.123537
2022-01-15 14:41:17,127 INFO    WriterThread:1956 [datastore.py:open_for_write():77] open: /Users/Eric/Documents/Uni/Msc/Courses/Sem1/CI/LAB/covid/models/CNN/wandb/offline-run-20220115_144115-1liwb2et/run-1liwb2et.wandb
2022-01-15 14:41:17,127 DEBUG   HandlerThread:1956 [handler.py:handle_request():130] handle_request: run_start
2022-01-15 14:41:17,130 DEBUG   HandlerThread:1956 [meta.py:__init__():40] meta init
2022-01-15 14:41:17,131 DEBUG   HandlerThread:1956 [meta.py:__init__():54] meta init done
2022-01-15 14:41:17,131 DEBUG   HandlerThread:1956 [meta.py:probe():214] probe
2022-01-15 14:41:17,138 DEBUG   HandlerThread:1956 [meta.py:_setup_git():204] setup git
2022-01-15 14:41:17,184 DEBUG   HandlerThread:1956 [meta.py:_setup_git():211] setup git done
2022-01-15 14:41:17,184 DEBUG   HandlerThread:1956 [meta.py:_save_pip():58] save pip
2022-01-15 14:41:17,185 DEBUG   HandlerThread:1956 [meta.py:_save_pip():72] save pip done
2022-01-15 14:41:17,186 DEBUG   HandlerThread:1956 [meta.py:_save_conda():79] save conda
2022-01-15 14:41:26,974 DEBUG   HandlerThread:1956 [meta.py:_save_conda():89] save conda done
2022-01-15 14:41:26,974 DEBUG   HandlerThread:1956 [meta.py:probe():252] probe done
2022-01-15 14:42:19,206 WARNING MainThread:1956 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-15 14:42:19,493 WARNING MainThread:1956 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-01-15 14:42:19,494 ERROR   MainThread:1956 [internal.py:wandb_internal():149] Internal process interrupted.
2022-01-15 14:42:19,874 INFO    MainThread:1956 [internal.py:handle_exit():77] Internal process exited
